### ISSUE TITLE
[0.74] Implement `RCTRootViewFactory`

### ISSUE THREAD

**Issue by okwasniewski** [reactwg/react-native-releases#120]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/42263

### Description

Hey, 

This changes the flow of initialization of React Native on iOS side and it's beneficial for brownfield scenarios. 

I've created a cherry-pick PR as the conflicts to resolve were not trivial: https://github.com/facebook/react-native/pull/43325

**Comment by huntie** [comment]
Picked ✅
