### ISSUE TITLE
[0.74] Pick Request - Cursor Style prop

### ISSUE THREAD

**Issue by Saadnajmi** [reactwg/react-native-releases#121]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43078

### Description

This prop was added to iOS but missed the 0.74 cut. It's a feature add that is useful for visionOS, as well as upstreams a previous desktop only prop that might be useful for web compatibility.

**Comment by Saadnajmi** [comment]
Looks like you'll also need to pick https://github.com/facebook/react-native/pull/43331 for Xocde 14.3 compatibility.

**Comment by huntie** [comment]
Picked (also #43331) ✅
