### ISSUE TITLE
[0.74] Cherry-pick "Expose `rrc_textinput` via prefab"

### ISSUE THREAD

**Issue by tomekzaw** [reactwg/react-native-releases#135]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43274

### Description

Without this PR it's impossible to include header files and link shared libraries related to `TextInput` component on Android.

**Comment by cortinico** [comment]
Picked in the 0.74 release branch, will be released in 0.74 RC3
