### ISSUE TITLE
[0.74] Add overridable hooks for bridgeless creation in RCTAppDelegate

### ISSUE THREAD

**Issue by Kudo** [reactwg/react-native-releases#148]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43402

### Description

not sure whether this is the right way to request the cherry-pick because the pr is based on 0.74 only. please take a look and see if that makes sense to have this.

**Comment by huntie** [comment]
Replaced with #43325

**Comment by Kudo** [comment]
cool sorry i missed that cherry-pick. thanks for the heads up.
