### ISSUE TITLE
[0.74][iOS] jsCallInvoker support in RCTBridgeProxy

### ISSUE THREAD

**Issue by philIip** [reactwg/react-native-releases#151]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

See comment below

### Description

This is part of the backwards compatibility layers to unblock bridgeless mode specificially. This is to resolve https://github.com/facebook/react-native/issues/43204

**Comment by cortinico** [comment]
@philIip @arushikesarwani94 there are 3 commits to pick here right? Can we list them

**Comment by arushikesarwani94** [comment]
> @philIip @arushikesarwani94 there are 3 commits to pick here right? Can we list them

For Android : https://github.com/facebook/react-native/pull/43400/commits/8b9dc7f32fd5012e6f3840e3c3607bd148ceebf3 followed by https://github.com/facebook/react-native/pull/43424/commits/534b594862d1597bcd0ff1bf33ea370ebd854bbe

For iOS : https://github.com/facebook/react-native/pull/43314/commits/5d5edcb1ea7a9cb0632fb6ff56811b8ad6a851fb & https://github.com/facebook/react-native/pull/43314/commits/90bcb214b9f2b1d4cfbda26bd9828de73d217426

If it's too much hassle, can aim for the next RC.

**Comment by philIip** [comment]
> > [@philIip](https://github.com/philIip) [@arushikesarwani94](https://github.com/arushikesarwani94) there are 3 commits to pick here right? Can we list them
> 
> For Android : [facebook/react-native@8b9dc7f](https://github.com/facebook/react-native/commit/8b9dc7f32fd5012e6f3840e3c3607bd148ceebf3) followed by [facebook/react-native@534b594](https://github.com/facebook/react-native/commit/534b594862d1597bcd0ff1bf33ea370ebd854bbe)
> 
> For iOS : [facebook/react-native@5d5edcb](https://github.com/facebook/react-native/commit/5d5edcb1ea7a9cb0632fb6ff56811b8ad6a851fb) & [facebook/react-native@90bcb21](https://github.com/facebook/react-native/commit/90bcb214b9f2b1d4cfbda26bd9828de73d217426)
> 
> If it's too much hassle, can aim for the next RC.

https://github.com/facebook/react-native/commit/90bcb214b9f2b1d4cfbda26bd9828de73d217426 is not needed to be picked

**Comment by cortinico** [comment]
> @cortinico can you push these picks in RC so I can test?

Next RC is happening on Monday 18th

**Comment by huntie** [comment]
Picked ✅, including preceding commits which added `BridgelessCatalystInstance`, with @cortinico.
