### ISSUE TITLE
[0.74] Bring back the UNSET constant to TextAttributeProps

### ISSUE THREAD

**Issue by dmytrorykun** [reactwg/react-native-releases#156]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43491

### Description

Fix for `lottie-react-native` build error in Bridgeless/Android.

**Comment by TheRogue76** [comment]
Much appreciated @dmytrorykun. Would be interesting to see which APIs the RN team wants to make private, so we can clean up library accesses and make sure we are not tapping into private APIs.
