### ISSUE TITLE
[0.74]: gradle-wrapper.jar is broken

### ISSUE THREAD

**Issue by AlirezaHadjar** [reactwg/react-native-releases#158]
### Old Version

0.74-rc.0

### New Version

0.74-rc.3

### Description

Hi everyone 👋 
When upgrading from 0.74-rc.0 to 0.74-rc.3, the download link of `gradle-wrapper.jar` file is broken.

Here is the `upgrade-helper` URL: 
https://react-native-community.github.io/upgrade-helper/?from=0.74.0-rc.0&to=0.74.0-rc.3

And here is the broken link:
https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.74.0-rc.3/RnDiffApp/android/gradle-wrapper.jar

### Steps to reproduce

1. open `upgrade-helper`
2. select 0.74-rc.1 as the current version and 0.74-rc.3 as the next version
3. pressing the download button of `gradle-wrapper.jar` file

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
nothing
```

### Stacktrace or Logs

```text
nothing
```

### Reproducer

https://react-native-community.github.io/upgrade-helper/?from=0.74.0-rc.0&to=0.74.0-rc.3

### Screenshots and Videos

<img width="1433" alt="Screenshot 2024-03-17 at 3 22 57 AM" src="https://github.com/reactwg/react-native-releases/assets/57192409/9d555a12-4c8d-4f7d-9bec-2714c502bcd4">

**Comment by cortinico** [comment]
> When upgrading from 0.74-rc.0 to 0.74-rc.3, the download link of `gradle-wrapper.jar` file is broken.

That happens because the file `android/gradle-wrapper.jar` was accidentally included in the template for RC0. We removed it here
https://github.com/facebook/react-native/commit/c7bacf610db1e04ec148a87ae4f1812db2472499

which is included inside RC1.

So it's correct that the link returns 404
