### ISSUE TITLE
[0.74] RC-only: Keep ES6Proxy enabled in bridgeless mode

### ISSUE THREAD

**Issue by fkgozali** [reactwg/react-native-releases#161]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43538

### Description

This is a regression in bridgeless vs the bridge, where the ES6Proxy for Hermes runtime was disabled by accident, causing https://github.com/facebook/react-native/issues/43523

Note that this is an RC-only pick, we cannot land it as is to main without bigger refactor (which will come in a later time).

**Comment by cortinico** [comment]
@fkgozali this commit is not in main so it can't be picked for RC5, and will make it into RC6

**Comment by fkgozali** [comment]
https://github.com/facebook/react-native/pull/43538 has landed properly in main, so please pick it to the 0.74-stable for the next RC

**Comment by huntie** [comment]
Picked ✅
