### ISSUE TITLE
[0.74] Create custom message handler for synthetic page

### ISSUE THREAD

**Issue by byCedric** [reactwg/react-native-releases#166]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43559

### Description

The new "custom message handler API" for the inspector proxy in React Native 0.74 seems to work great (see https://github.com/reactwg/react-native-releases/issues/128).

Unfortunately, there was 1 oversight for the synthetic page system. This PR also instantiates the custom message handler API for the synthetic page -- the one with a stable page ID (`-1`).

**Comment by huntie** [comment]
Picked ✅
