### ISSUE TITLE
[0.74] Provide descriptive message when building with too old version of XCode

### ISSUE THREAD

**Issue by NickGerleman** [reactwg/react-native-releases#170]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/1021448d7cf462d5280ce82f484f029fd29e40a6

### Description

Users get a confusing error message when trying to build 0.74 with versions of XCode before 14.3. This adds a better message to make the problem clear.

**Comment by huntie** [comment]
Picked ✅
