### ISSUE TITLE
[0.73] Fix Android HorizontalScrollView fling when content length less than ScrollView length

### ISSUE THREAD

**Issue by NickGerleman** [reactwg/react-native-releases#171]
### Target Branch(es)

0.73

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/7d180d7127e30cfdf2213e088b79e11b55866816

### Description

Old bug, inadvertently exposed by another fix that made it into 0.73.

**Comment by cortinico** [comment]
Moving this to 0.73 only as for 0.74 we have this other pick request:
https://github.com/reactwg/react-native-releases/issues/175

**Comment by efstathiosntonas** [comment]
@alfonsocj this one too should be closed since it's picked
