### ISSUE TITLE
[0.74] Implement multiple view manager lookup for the interop layer on Android

### ISSUE THREAD

**Issue by gabrieldonadel** [reactwg/react-native-releases#172]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/15a5638c621cbec4a9fcb5ae94938120cdc32fae

### Description

When running with the new architecture on and using the renderer interop layer on Android, view managers don't work if their names start with `RCT`. This happens because the `RCT` prefix is automatically removed from the component name, and inside the internal `mViewManagers` we store view managers with the `RCT` prefix.

**Comment by huntie** [comment]
Picked ✅
