### ISSUE TITLE
[0.74] fix(iOS): add missing forward blocks to RCTRootViewFactory

### ISSUE THREAD

**Issue by Kudo** [reactwg/react-native-releases#177]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43638

### Description

fix RCTRootViewFactory regression. the pr is already based on 0.74-stable and cherry-pick two fixes that recommended [here](https://github.com/facebook/react-native/pull/43526#issuecomment-2014954813)

**Comment by huntie** [comment]
Merged ✅

**Comment by huntie** [comment]
Reverted ❗This change appeared to break iOS tests (`RNTestProject`, i.e. E2E project creation with RN CLI). Let's look at getting this fixed and picked again for RC6.

**Comment by okwasniewski** [comment]
Ugh, sorry - I'll try to figure out what's wrong with this tomorrow

**Comment by Kudo** [comment]
apologize for not checking correctly.
the problem was coming from the implementation 
https://github.com/facebook/react-native/blob/00725fadff28bb3c7fed65f208e647f0dab69e75/packages/react-native/React/CxxBridge/RCTCxxBridge.mm#L519-L540

we should dynamically override `loadSourceForBridge:onProgress:onComplete:` and `loadSourceForBridge:withBlock:` in RCTRootViewFactory only when AppDelegate override it. one way to achieve this might be tricky that we may need to override `respondsToSelector:`.

otherwise, we could just skip the `loadSourceForBridge:onProgress:onComplete:` and `loadSourceForBridge:withBlock:` support.

**Comment by okwasniewski** [comment]
Hey @Kudo, I've opened a PR to remove those blocks for now - it's better to at least have support for the basic ones like (`sourceURLForBridge`) and figure out how to make `loadSourceForBridge:` work in some later patch to 0.74

**Comment by cortinico** [comment]
> and figure out how to make loadSourceForBridge: work in some later patch to 0.74

Makes sense 👍 Also @cipolleschi can help here once he's back
