### ISSUE TITLE
[0.74] use_ccache is broken on iOS

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#180]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43634

### Description

The `use_ccache` directive is broken on 0.74 due to missing scripts in the package.json.
See related issue here: https://github.com/facebook/react-native/issues/43633

**Comment by blakef** [comment]
To give the picker context, if you enable this feature your iOS builds will consistently fail.

**Comment by huntie** [comment]
Picked ✅
