### ISSUE TITLE
[0.74] Fix @react-native/popup-menu-android outside of Flow

### ISSUE THREAD

**Issue by NickGerleman** [reactwg/react-native-releases#181]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/dbf8e3f5ba8636560898803f5c5973432bf61d1e

### Description

@react-native/popup-menu-android is new in 0.74. Commit above fixes incorrect paths in TS types. Also fixes longer running bug causing issues with pnpm.

**Comment by NickGerleman** [comment]
I think this was a drive-by fix, and looking at the TS definitions, I'm not sure they will work.

@rsnara this might be worth taking a look at, if the intention is that this package is usable from OSS.

**Comment by huntie** [comment]
Picked ✅
