### ISSUE TITLE
[0.74] Fix react-native-restart in RELEASE

### ISSUE THREAD

**Issue by arushikesarwani94** [reactwg/react-native-releases#184]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43645/

### Description

https://github.com/facebook/react-native/pull/43521 & https://github.com/facebook/react-native/pull/43588 aimed to fix `react-native-restart`, however in RELEASE `handleReloadJS()` is a no-op in [DisabledDevSupportManager](https://github.com/facebook/react-native/blob/ac714b1c3300d3a169bdcfec05d556e18a7b83ff/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/devsupport/DisabledDevSupportManager.java#L139) which is why this should not work. Fixing it by relying on ReactHostImpl.reload() instead for Bridgeless.

**Comment by huntie** [comment]
Picked ✅
