### ISSUE TITLE
[0.74] eslint: Update @typescript-eslint monorepo to v7 & eslint-plugin-jest to v27 

### ISSUE THREAD

**Issue by lluiscab** [reactwg/react-native-releases#194]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43406

### Description

Publishing `@react-native/eslint-config@0.74.78` with the dependencies updated at https://github.com/facebook/react-native/pull/43406 would resolve various issues that occur in monorepos that use / have multiple versions of `@typescript-eslint` packages in use by other eslint plugins & configs. This is currently the major roadblock in updating to `@typescript-eslint@7` in our internal eslint config packages.

We for example, can't really update `eslint-plugin-jest` to `27.0.0` due to issues caused when both `eslint-plugin-jest@27` and `eslint-plugin-jest@26` are installed in the same monorepo

**Comment by cortinico** [comment]
I've discussed this internally with @robhogan and we've decided to don't pick this change on the 0.74 release branch, at least for now. The rationale is that this is a major version bump of a dependency.

Realistically, this could result in more warnings for the end users, so no real impact on the final apps. But at the same time, this pick request is coming really late in the stabilisation process of 0.74 (we're at RC7 which we expect to be the Golden RC) and we don't want to include major version bumps in the last RC.

**Comment by lluiscab** [comment]
I'm not familiarized with the react-native release process, given that these changes are already in the `react-native` repository, what will be your first release in which they will be included? Do I need to open a pick request for any other versions? 0.75?

**Comment by cortinico** [comment]
> I'm not familiarized with the react-native release process, given that these changes are already in the `react-native` repository, what will be your first release in which they will be included? Do I need to open a pick request for any other versions? 0.75?

They will be included automatically in 0.75 👍  There is no need to file a pick request

**Comment by huntie** [comment]
Intending to test + pick for 0.74.1.

**Comment by cortinico** [comment]
> Intending to test + pick for 0.74.1.

I believe we discussed to don't include this in 0.74 as they're a major version bump of a dependency. Are we changing our stance here?

**Comment by cortinico** [comment]
> I believe we discussed to don't include this in 0.74 as they're a major version bump of a dependency. Are we changing our stance here?

@robhogan cc

**Comment by huntie** [comment]
Merged https://github.com/facebook/react-native/pull/44764
