### ISSUE TITLE
[0.74, 0.73] Add build settings to every Debug custom build configuration

### ISSUE THREAD

**Issue by jblarriviere** [reactwg/react-native-releases#195]
### Target Branch(es)

0.74, 0.73

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43780

### Description

This change enables the experimental new debugger for iOS apps with custom build configuration (matching \*Debug\*)

**Comment by cortinico** [comment]
✅ Picked, this will land in 0.74 RC7
