### ISSUE TITLE
[0.74][Yoga] Fix archive for MacOS Catalyst 

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#198]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43900

### Description

Following up https://github.com/facebook/react-native/issues/41938, this PR targeting 0.74 will fix an archiving issue for the Yoga pod.

**Comment by cortinico** [comment]
✅ Picked, this will land in 0.74 RC7
