### ISSUE TITLE
[0.74] [iOS] FixRCTComposedViewRegistry for Old Arch by adding `count` and `keyEnumerator`

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#200]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/82b58d0367cb89f41427950ad406dee61f61a8ba

### Description

This is a fix requested by SWM to make lottie-react-native work back in the Old Architecture.

**Comment by cortinico** [comment]
✅ Picked, this will land in 0.74 RC7
