### ISSUE TITLE
[0.74] Remove invalidate observer instead of re-adding observer in DeviceInfo module

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#202]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/91279a822be949051866a694148e509c1308035b

### Description

This is a fix for a typo I made in a previous change. Basically, instead of removing an observer in the `invalidate` method, I was adding it. 🤦

**Comment by cortinico** [comment]
✅ Picked, this will land in 0.74 RC7
