### ISSUE TITLE
[0.74] Support launchOptions in bridgeless mode

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#206]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/90296be1d4fab09a52e02dd09f34f819136d0a07

### Description

Support `launchOptions` in bridgeless mode to fix universal and deep links on iOS.

**Comment by cortinico** [comment]
@cipolleschi this merge conflicts on those files:

```
	both modified:   packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTInstance.h
	both modified:   packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTInstance.mm
	both modified:   packages/react-native/ReactCommon/react/test_utils/ios/Shims/ShimRCTInstance.mm
```

could you send a PR?

**Comment by cortinico** [comment]
✅ Picked, this will land in 0.74 RC8
