### ISSUE TITLE
[0.74] Make the Open Debugger option appear in Bridgeless mode

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#223]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/18916f391a63f8eb454d007f97be4dcdd8ae5ef4

### Description

After a [recent change](https://github.com/facebook/react-native/commit/90296be1d4fab09a52e02dd09f34f819136d0a07) we break part of the integration with the debug menu, which is was using the presence/absence of the bridge to decide whether we were in bridge or bridgeless.

For backward compatibility reasosn, the bridge ivar is now populated with the bridgeProxy, so just checking whether is nil or not is not enough to verify whether we are in bridge or in bridgeless mode anymore.

**Comment by huntie** [comment]
Picked ✅
