### ISSUE TITLE
[0.74] Change bridgeless check in dev menu

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#224]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43976

### Description

We would set the value of _bridge ivar to bridgeProxy for turbo module in bridgeless mode in https://github.com/facebook/react-native/pull/43757 , so we need to change the way of bridgeless/bridge check

**Comment by cipolleschi** [comment]
This has landed, in case the original PR to cherry-pick remains open!

**Comment by huntie** [comment]
Picked ✅
