### ISSUE TITLE
[0.74] getRuntimeExecutor() for BridgelessCatalystInstance

### ISSUE THREAD

**Issue by arushikesarwani94** [reactwg/react-native-releases#227]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44053

### Description

Implement `getRuntimeExecutor()` for BridgelessCatalystInstance

Changelog:
[Android][Breaking] Implement `getRuntimeExecutor()` for Bridgeless Catalyst Instance

**Comment by huntie** [comment]
Picked ✅
