### ISSUE TITLE
Latest version 0.74, npm WARN ERESOLVE overriding peer dependency

### ISSUE THREAD

**Issue by TonyFTannous** [reactwg/react-native-releases#239]
### Old Version

0.73.7

### New Version

0.74

### Description

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-plugin-jest@26.9.0
npm WARN Found: @typescript-eslint/eslint-plugin@6.21.0
npm WARN node_modules/@typescript-eslint/eslint-plugin
npm WARN   @typescript-eslint/eslint-plugin@"^6.7.4" from @react-native/eslint-config@0.74.81
npm WARN   node_modules/@react-native/eslint-config
npm WARN     dev @react-native/eslint-config@"0.74.81" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional @typescript-eslint/eslint-plugin@"^5.0.0" from eslint-plugin-jest@26.9.0
npm WARN node_modules/eslint-plugin-jest
npm WARN   eslint-plugin-jest@"^26.5.3" from @react-native/eslint-config@0.74.81
npm WARN   node_modules/@react-native/eslint-config
npm WARN 
npm WARN Conflicting peer dependency: @typescript-eslint/eslint-plugin@5.62.0
npm WARN node_modules/@typescript-eslint/eslint-plugin
npm WARN   peerOptional @typescript-eslint/eslint-plugin@"^5.0.0" from eslint-plugin-jest@26.9.0
npm WARN   node_modules/eslint-plugin-jest
npm WARN     eslint-plugin-jest@"^26.5.3" from @react-native/eslint-config@0.74.81
npm WARN     node_modules/@react-native/eslint-config

### Steps to reproduce

1. create new app npx react-native@latest init AwesomeProject
2. npm install

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
  Memory: 70.09 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.2
    path: ~/.nvm/versions/node/v20.12.2/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v20.12.2/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.2
      - 33.0.3
      - 34.0.0
    System Images:
      - android-31 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11668458
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

https://reactnative.dev/docs/environment-setup

**Comment by huntie** [comment]
@TonyFTannous Thanks for reporting this. Can confirm this warning is introduced in 0.74.0. As far as I can tell, this does not block an `npm install`, but I'll see if we can successfully bring over the recent `@typescript-eslint/eslint-plugin` bump (https://github.com/facebook/react-native/commit/91d725136e8fe0fd55fdfca5a4f5bd8ab527f94e) to fix this.

**Comment by robhogan** [comment]
FYI @huntie, there was already a pick request for this which we rejected as it was very late in the RC, but I didn't realise these warnings would be the consequence: https://github.com/reactwg/react-native-releases/issues/194

**Comment by kbqdev** [comment]
![Screenshot 2024-05-29 at 14 06 35](https://github.com/reactwg/react-native-releases/assets/87011701/ba278973-9399-4172-9f3d-59ffe93f1549)
Version 0.74.1
More issues. OMG

**Comment by huntie** [comment]
Merged https://github.com/facebook/react-native/pull/44764. This will ship in 0.74.2.

**Comment by kbqdev** [comment]
Still exist. i'm trying create new project -> remove node_module package-lock.json -> npm install.
Still same 0.74.1

**Comment by cortinico** [comment]
> Still same 0.74.1

This is fixed in 0.74.2

**Comment by kbqdev** [comment]
<img width="698" alt="Screenshot 2024-06-15 at 21 26 51" src="https://github.com/reactwg/react-native-releases/assets/87011701/d0d9ecab-431a-44c0-837f-240f43bd48c8">
It's not

**Comment by cortinico** [comment]
> <img alt="Screenshot 2024-06-15 at 21 26 51" width="698" src="https://private-user-images.githubusercontent.com/87011701/339996716-d0d9ecab-431a-44c0-837f-240f43bd48c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjAwODUsIm5iZiI6MTcxODYxOTc4NSwicGF0aCI6Ii84NzAxMTcwMS8zMzk5OTY3MTYtZDBkOWVjYWItNDMxYS00NGMwLTgzN2YtMjQwZjQzYmQ0OGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwMjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ODEyYTI0NmMyNmRiOTBiMTk2NWNmODEzYTZmY2ExNDQxOTVhOTU1NGI2ZmVhNTYyZjlhMjE3M2JiYjFhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SYWp0PxrZqjsHiIu9qFsymmWkM-fWIkc7NlbCR9Y1vs"> It's not

Your error message is different from the original one in the first post: `ERESOLVE overriding peer dependency` so yes it's solved.
