### ISSUE TITLE
[0.74] CLI bump - properly bump Yarn version in new projecrts

### ISSUE THREAD

**Issue by szymonrybczak** [reactwg/react-native-releases#244]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44253

### Description

There was a regression, where in some scenarios `init` command didn't properly bump Yarn version, this bump contains a version with fix for it.

**Comment by szymonrybczak** [comment]
This should land in 0.74.1, this regression blocks bumping Yarn in most cases.

**Comment by cipolleschi** [comment]
picked ✅
