### ISSUE TITLE
[0.74][iOS] trigger RCTContentDidAppearNotification when content appears on bridgeless

### ISSUE THREAD

**Issue by Kudo** [reactwg/react-native-releases#246]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43823

### Description

need this to unblock expo-splash-screen support on bridgeless. my [previous fix](https://github.com/expo/expo/pull/28234) was reverted because the RCTContentDidAppearNotification send earlier before native modules initialized.
the expo-splash-screen on bridgeless mode now is not fully working. the splash screen is still there but behinds the content view.

**Comment by cipolleschi** [comment]
picked ✅
