### ISSUE TITLE
[0.73] Add privacy manifest to hello world template

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#262]
### Target Branch(es)

0.73

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/42978

### Description

Add the PrivacyManifest to the Template

**Comment by Titozzz** [comment]
Picked the 0.72 commit following advice from @cipolleschi 

Picked here: https://github.com/facebook/react-native/commit/12da0cda4c326f2c3b3b0d0de86944852a683e2f
