### ISSUE TITLE
[0.74][iOS] Optimize RCTUIManager to avoid too many calls to viewForReactTag

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#266]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/15f0895b857bdd452381ff340a7a04ff93a37b97

### Description

This change fixes a couple of issues within the RCTUIManager:
* it calls the right method in the `super` branches (although they should neve be executed)
* it invert the call order between the `_registry` and the `uiManager` to avoid extra calls into the `viewForReactTag`.

**Comment by cipolleschi** [comment]
picked ✅

**Comment by cortinico** [comment]
> hi, after the rn upgrade to 0.74.0 we are suffering this issue too according to Crashlytics, it will be merged any time soon?

This was included in 0.74.1, you should update to it to get it resovled
