### ISSUE TITLE
[0.74] Support more stubbed methods in BridgelessCatalystInstance 

### ISSUE THREAD

**Issue by arushikesarwani94** [reactwg/react-native-releases#274]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/5e7f74d3a241b92420f1cf3efb35dfbc421a0338

### Description

This PR provides support for 6 APIs in BridgelessCatalystInstance making them backwards compatible :
- [getNativeModule(nativeModuleInterface: Class<T>)](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt#L104-L105)
- [getNativeModule(moduleName: String)](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt#L107-L108) 
- [hasNativeModule(nativeModuleInterface: Class<T>)](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt#L101-L102)
- [getNativeModules](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt#L117)
- [getReactQueueConfiguration](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt#L95-L97)
- [getJSModule](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt#L98-L99)

**Comment by cipolleschi** [comment]
picked ✅
