### ISSUE TITLE
[0.74] 'selection' prop does not work on Android on TextInput component initialization

### ISSUE THREAD

**Issue by alanleedev** [reactwg/react-native-releases#283]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44398

### Description

Bugfix:  The PR fixes an issue with `selection` prop passed in being ignored when TextInput component is being initialized. Fixes bug reported in https://github.com/facebook/react-native/issues/44171

**Comment by cipolleschi** [comment]
Picked ✅
