### ISSUE TITLE
'RCTAppDelegate.h' file not found  

### ISSUE THREAD

**Issue by MoamberRaza** [reactwg/react-native-releases#285]
### Old Version

0.74.0

### New Version

0.74.1

### Description

Incase of multiple Scheme in IOS, base Scheme would work fine but would not work when you select 2nd or any other scheme if you have in your project it would throw  

'RCTAppDelegate.h' file not found

in-case you create new scheme it would start working but not properly synched with current 2nd Scheme.

<img width="983" alt="Screenshot 2024-05-08 at 17 34 09" src="https://github.com/reactwg/react-native-releases/assets/52427232/a2403a6c-5dc7-44ff-bb6a-b242571d8d86">

### Steps to reproduce

create project with 0.74.0 
create new scheme 
upgrade to 0.74.1
error with generated.

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 41.53 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.7.0
    path: ~/.nvm/versions/node/v19.7.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.0
    path: ~/.nvm/versions/node/v19.7.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/developer/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "28"
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    System Images:
      - android-28 | Google APIs Intel x86_64 Atom
      - android-29 | Google APIs Intel x86_64 Atom
      - android-33 | Google APIs Intel x86_64 Atom
      - android-33 | Google Play Intel x86_64 Atom
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11668458
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/developer/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: ^0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
'RCTAppDelegate.h' file not found
```

### Reproducer

https://domain.com

**Comment by cortinico** [comment]
> ### Old Version
> 0.74.0
> 
> ### New Version
> 0.74.1

Was this working fine on 0.74.0 and then broke in 0.74.1?

**Comment by MoamberRaza** [comment]
@cortinico  Yes, currently i moved back to 0.74.0 to make it run but in case of 0.74.1 it wont be. 
this issue i faced when i had tried 0.73.0 to 0.73.1 up-gradations. (just for reference)

**Comment by MoamberRaza** [comment]
target 'MyApp' do
  config = use_native_modules!

...

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # 👇 Add your target in the Podfile
  target 'MyApp (dev)' do
    inherit! :complete
  end

...


This might work for those who are having issues. i cannot regenerate issue to verify because project is now running and synced. Thanks.
