### ISSUE TITLE
[0.74.1] Cherry-pick Hermes atob padding fix

### ISSUE THREAD

**Issue by hirbod** [reactwg/react-native-releases#287]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/hermes/issues/1379

### Description

base64 decoding fails if the provided string does not contain padding. This is breaking our app.
As a workaround I added following function to add padding before trying to decode.

```ts
function ensureBase64Padding(base64: string) {
    const paddingNeeded = (4 - base64.length % 4) % 4;
    return base64 + '='.repeat(paddingNeeded);
}
```

Kindly asking to cherry-pick this fix.

**Comment by cipolleschi** [comment]
Picked ✅
