### ISSUE TITLE
Intl library functions become undefined on iOS in React Native v0.74.x with Hermes

### ISSUE THREAD

**Issue by rcluca** [reactwg/react-native-releases#290]
### Old Version

0.73.8

### New Version

0.74.1

### Description

The built-in `Intl` library seems to lose support on iOS with Hermes in v0.74.x, specifically methods like `Intl.DateTimeFormat.formatToParts()` become undefined. Android (with and without Hermes) and Web work as expected.

### Steps to reproduce

1. Install the app with `yarn install` and `pod install` in the `ios` repo
2. Add a reference to the `Intl` library and use it, for example, add the following to the `App.tsx` file:
`const formatter = new Intl.DateTimeFormat();
  console.log(formatter.formatToParts(new Date()));`
3. Run the app with `react-native start` and `react-native run-ios`.
4. See the app crash when loading the `App` component.

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.6.6
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 102.14 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.4.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 9.2.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.01.16.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/raulluca/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/raulluca/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
LOG  Running "ReproducerApp" with {"rootTag":1,"initialProps":{"concurrentRoot":false}}
 ERROR  TypeError: formatter.formatToParts is not a function (it is undefined)

This error is located at:
    in Section (created by App)
    in RCTView (created by View)
    in View (created by App)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by App)
    in RCTSafeAreaView (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in ReproducerApp(RootComponent), js engine: hermes
```

### Reproducer

https://github.com/rcluca/intl-hermes

### Screenshots and Videos

<img width="381" alt="Error Screen" src="https://github.com/reactwg/react-native-releases/assets/8628789/f82a5694-2ed6-4425-b7db-abc89df0198d">

**Comment by dmytrorykun** [comment]
This regression was first introduced in `0.74.0-nightly-20231018-191c3deae`

**Comment by dmytrorykun** [comment]
This regression was introduced here https://github.com/facebook/hermes/commit/c5a633f6452902cd0b5c9392a1e4f51a33933284

**Comment by cipolleschi** [comment]
We picked the revert for 0.74.2.

**Comment by thespacemanatee** [comment]
@cipolleschi, can we pick this revert for 0.76 as well? It has started to break for us again, and we use it in our projects. Are we advised to use alternative APIs?

**Comment by cipolleschi** [comment]
@thespacemanatee I'm sorry for that. We will revert the commit commit on 0.76 again. Meanwhile, I'll try to find a more sustainable long term solution.

**Comment by maksim-romanov** [comment]
same issue for me, `formatRange` is `undefined` too

**Comment by G2Jose** [comment]
Hey this still seems to be a problem (in react native 0.79.3)
