### ISSUE TITLE
[0.74] Fix for Unhandled SoftException - `com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange`

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#291]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/ac3261ff608768ff43736b413c5a5ad67668af61

### Description

This fixes a warning the user see on console on bridgeless.
See https://github.com/facebook/react-native/issues/44251 for more context

**Comment by rjkarthik** [comment]
Still seeing this in 0.76.2

**Comment by MarcelinaZiolkiewicz** [comment]
+1

**Comment by cortinico** [comment]
This is a pick request, don't comment here but please open an issue on facebook/react-native
