### ISSUE TITLE
[0.74] Fix bridgeless triggering reloads twice from `BridgelessDevSupportManager`

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#295]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/524e3eec3e73f56746ace8bef569f36802a7a62e

### Description

Noticed than when reload is triggered by Metro (`handleReloadJS`), the application would often get stuck and not respond to further reload commands. Often an IOException would get printed as well, due to concurrent bundle loads happening.

**Comment by cortinico** [comment]
We won't be picking this as it introduces a breaking change in a patch version + @Kudo mentioned there is a workaround in place for Expo
