### ISSUE TITLE
[0.74] Increase iOS script portability

### ISSUE THREAD

**Issue by leotm** [reactwg/react-native-releases#296]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44417

### Description

CocoaPods can only be installed (`pod install`) on macOS, this fixes it for Linux.
Useful for e.g. Ubuntu CI images to validate `Podfile.lock`, auditing, experimental development, etc.

**Comment by cipolleschi** [comment]
Picked ✅
