### ISSUE TITLE
[0.74] Fix Privacy Manifest generator when it does not contain a NSPrivacyAccessedAPITypes key

### ISSUE THREAD

**Issue by renchap** [reactwg/react-native-releases#297]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44628

### Description

This fixes an issue with PrivacyManifests from dependencies do not include a `NSPrivacyAccessedAPITypes` key.

**Comment by cipolleschi** [comment]
Picked ✅
