### ISSUE TITLE
[0.73] Remove invalidate observer instead of re-adding observer in DeviceInfo module

### ISSUE THREAD

**Issue by Saadnajmi** [reactwg/react-native-releases#302]
### Target Branch(es)

0.73

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/91279a822be949051866a694148e509c1308035b

### Description

We saw a pretty major hang internally, seemingly caused by https://github.com/facebook/react-native/commit/d46d80d2ef6cdc05c5a1b2429ed1df93410ae36f . The linked commit seems to fix the issue, so let's get it back ported to supported versions! Related: https://github.com/microsoft/react-native-macos/pull/2130

**Comment by gabrieldonadel** [comment]
Picked ✅
