### ISSUE TITLE
[0.74] Continue running microtasks when parent task throws

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#310]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/db1043dfbf15b8d2e39eeb50b315384aa39e4606

### Description

We found an incorrect behavior in the event loop, where an error in a task would prevent its microtasks from running. This isn't spec compliant and should be fixed.

This caused LogBox to not work correctly, as error reporting is implemented via microtasks that would never execute.

**Comment by Titozzz** [comment]
Picked ✅

**Comment by Titozzz** [comment]
Also picked 
- https://github.com/facebook/react-native/commit/d35de2d043c2b73bc7af8af596d2b0ed5f327b4f
- https://github.com/facebook/react-native/commit/3094273e8bfa2bfa46f7e5a203cd98b9af684bb0

on recommendation from @cipolleschi
