### ISSUE TITLE
[0.74] Support customizeRootView from RCTRootViewFactory

### ISSUE THREAD

**Issue by Kudo** [reactwg/react-native-releases#312]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44775

### Description

please help to pick this change and then we could remove the local patch from [react-conf-app](https://github.com/expo/react-conf-app/blob/main/patches/expo-modules-core%2B1.12.11.patch). thanks!

**Comment by Titozzz** [comment]
Picked ✅
