### ISSUE TITLE
[0.74] Fix Multiline TextInput with a fixed height scrolls to the bottom when prepending new lines to the text 

### ISSUE THREAD

**Issue by fabOnReact** [reactwg/react-native-releases#314]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/f6badca2f9a5f1e986dd76444bebde0d6049513d

### Description

Commit [6049513d](https://github.com/facebook/react-native/commit/f6badca2f9a5f1e986dd76444bebde0d6049513d)  fixes the following issue with multiline TextInput:

- Multiline TextInput scrolls to the bottom of the screen when prepending new lines to the text.

Could you please pick this commit? Thanks

| Before    | After |
| ----------- | ----------- |
| <video src="https://github.com/facebook/react-native/assets/24992535/e06b31fe-407d-4897-b608-73e0cc0f224a" width="350" />      | <video src="https://github.com/facebook/react-native/assets/24992535/fa2eaa31-c616-43c5-9596-f84e7b70d80a" width="350" />       |

**Comment by Titozzz** [comment]
Picked ✅
