### ISSUE TITLE
[0.74] Tentative fix for NPE JavaTimerManager$IdleCallbackRunnable.cancel

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#316]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/e686b4330d0a69fe78008b7eac86c54c9f96ee79

### Description

This is a pick request for a fix of:
- https://github.com/facebook/react-native/issues/44842

And

**Comment by Titozzz** [comment]
Picked ✅
