### ISSUE TITLE
Release 0.75.0

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#317]
### Target Minor

0.75.0

### Release Checklist

See [Release Process](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md) documentation

- [x] [Complete picks](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-2-cherry-pick-or-merge-requests-against-release-branch)
  - See [framework to evaluate priority of picks](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md#release-issues-and-pick-request-escalation)
- [x] (If < 0.74) [Publish monorepo packages](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-3-publish-monorepo-packages)
- [x] [Push things remote to get assets (like Hermes) ready](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-4-build-artifacts-on-circleci)
- [x] Test release (create [Test Report](https://github.com/reactwg/react-native-releases/issues/new/choose))
- [x] (If > 0.74) [Publish monorepo packages](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-6-publish-monorepo-packages)
- [x] [Publish `react-native`](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-7-publish-react-native)
- [ ] [Verify release](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-8-verify-release)
- [x] [Update Changelog](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-9-generate-the-changelog-pr)
- [x] [Create Github Release](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-10-create-the-github-release)
- [ ] [Announce it](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-11-communicate-release)
- [ ] [Update podfile.lock](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-12-update-podfilelock-on-the-release-branch)
- [ ] Update any Github Projects

**Comment by mikeduminy** [comment]
We would love to get [this hermes change](https://github.com/facebook/hermes/commit/20b13b96f49c6819f6090f17a5ec29d3faec45c6) cherry-picked into the 75 release, as well as 74 and 73. It fixes a crash when processing large JS bundles on-device (like loading a large app in dev mode) and should be safe to cherry-pick as it contains isolated changes (see https://github.com/facebook/hermes/issues/1448#issuecomment-2260655659).

**Comment by cortinico** [comment]
> We would love to get [this hermes change](https://github.com/facebook/hermes/commit/20b13b96f49c6819f6090f17a5ec29d3faec45c6) cherry-picked into the 75 release, as well as 74 and 73. It fixes a crash when processing large JS bundles on-device (like loading a large app in dev mode) and should be safe to cherry-pick as it contains isolated changes (see [facebook/hermes#1448 (comment)](https://github.com/facebook/hermes/issues/1448#issuecomment-2260655659)).

Cherry picks needs to be opened as separate issues here:
https://github.com/reactwg/react-native-releases/issues/new/choose

**Comment by cipolleschi** [comment]
There is an issue with the Template that prevents us from verifying the release.
0.75.0 can't create a new project. 😭

**Comment by cortinico** [comment]
> There is an issue with the Template that prevents us from verifying the release.
> 0.75.0 can't create a new project. 😭

Small heads up: we're going to follow up with 0.75.1 tomorrow morning right away (it will also include 2 picks that didn't make the .0 cut)

**Comment by arasruislam** [comment]
https://github.com/facebook/react-native/issues/46028
