### ISSUE TITLE
[0.72] [iOS] [Privacy Manifest] Cherry-pick fix for privacy manifest generation path being nil

### ISSUE THREAD

**Issue by miallo** [reactwg/react-native-releases#326]
### Target Branch(es)

0.72

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44410

### Description

With 0.72.15 running `pod install` will fail if you have ".strings" files (see linked PR)

**Comment by miallo** [comment]
Already picked to branch `0.72-stable` with commit https://github.com/facebook/react-native/commit/b5b3f3c43d02dc552c0884f9cee416c68b6eaea2 - only new release containing it is missing

**Comment by cipolleschi** [comment]
Picked ✅
