### ISSUE TITLE
[0.74] Back out "Add Float and Int type support for Android modules" 

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#328]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/8a6b88eeafef4eb63ee537c4ce71f9928f81a766

### Description

This fixes a regression in codegen for 0.74, so we should pick it.
More details on https://github.com/facebook/react-native/issues/44963

**Comment by Titozzz** [comment]
Picked in https://github.com/facebook/react-native/commit/278823ecc5783d187339b0aeafaaea0f9cb96d4a
