### ISSUE TITLE
[0.74] Build visionos hermes binary on the CI

### ISSUE THREAD

**Issue by okwasniewski** [reactwg/react-native-releases#330]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44691

### Description

This PR implements CI/CD for Hermes on visionOS. We want to provide react native visionOS users the ability to use prebuilts from a trusted source (in this case React Native). 

This change won't affect any of RN source code but it makes sure that the shipped hermes binary for the next version includes visionOS slice.

Here is a corresponding cherry-pick PR to `rn/0.74-stable` branch: https://github.com/facebook/hermes/commit/7701f77717171a5a778c2c7657b78ab77c637ead to make sure everything works correctly.

**Comment by okwasniewski** [comment]
Here is the cherry-pick: https://github.com/facebook/react-native/pull/45124

**Comment by Titozzz** [comment]
FYI: this will be in 0.74.4 instead of 0.74.3 as its ready to go and we'd prefer having Riccardo (currently OOO) when we merge this.

**Comment by okwasniewski** [comment]
@Titozzz That's fine for me, thanks

**Comment by Titozzz** [comment]
picked !
