### ISSUE TITLE
[0.75] add default 'ReactJsExceptionHandler' replacing a stub implmentation

### ISSUE THREAD

**Issue by alanleedev** [reactwg/react-native-releases#333]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44922

### Description

Trying to pick this change so it can be tested earlier before we enable new arch by default

**Comment by cortinico** [comment]
@alanleedev is this a bugfix? Can you explain why this is needed in 0.75?

**Comment by alanleedev** [comment]
> @alanleedev is this a bugfix? Can you explain why this is needed in 0.75?

@cortinico This isn't a bugfix but just trying to get this change in earlier so it can be tested before we enable new arch by default for all.

**Comment by cortinico** [comment]
We'll probably include this in 0.75, but just a heads up that this is breaking Expo as well as other OOT platforms: https://github.com/search?type=code&q=%22ReactHostImpl%28%22+NOT+is%3Afork&p=1
