### ISSUE TITLE
[0.74] Fix output path for generated artifacts

### ISSUE THREAD

**Issue by dmytrorykun** [reactwg/react-native-releases#335]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45165

### Description

Codegen computes output path relative to project root instead of current working directory.
Fix for https://github.com/facebook/react-native/issues/45112

**Comment by Titozzz** [comment]
Picked in https://github.com/facebook/react-native/commit/bdf6583c7e5538648e624afd0883aaf392b7eef8
