### ISSUE TITLE
[0.74] Add ReactMarkerConstants.CONTENT_APPEARED support on Android

### ISSUE THREAD

**Issue by Kudo** [reactwg/react-native-releases#337]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43620

### Description

expo-updates relies this to determine if the new update does not have launch crash. it would be good to have this and have feature parity on new architecture.

**Comment by Titozzz** [comment]
Picked in [3c4d7618f00751b08f73ffcec9ef1f69d44136da](https://github.com/facebook/react-native/commit/3c4d7618f00751b08f73ffcec9ef1f69d44136da) (& [3d53992051f698665b93a0d2747aaa75b51f3af5](https://github.com/facebook/react-native/commit/3d53992051f698665b93a0d2747aaa75b51f3af5) _due to a merge conflict poorly resolved by me_)
