### ISSUE TITLE
[0.73] Migrate executors to M1s on CCI

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#344]
### Target Branch(es)

0.73

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45214

### Description

CircleCI is deprecating Intel machines for iOS starting [from today - June 28](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718).
This PR migrate the iOS machines from Intel to M1s.

**Comment by gabrieldonadel** [comment]
Picked ✅
