### ISSUE TITLE
[0.75] Add missing `WithRuntimeDecorator` methods

### ISSUE THREAD

**Issue by bartlomiejbloniarz** [reactwg/react-native-releases#349]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/218ea5d44cae5774b1445cbc9e07d1ea3ef773d1

### Description

This PR fixes Reanimated crashes on the New Architecture that were caused by accessing the UI runtime concurrently.

**Comment by cortinico** [comment]
Just a small heads that I believe this pick requires a pick also on the hermes side: 
https://github.com/facebook/hermes/commit/6c859d790537ade6d10cd3f06f03c62f8f56188c

As otherwise the `jsi.h` file will diverge

**Comment by bartlomiejbloniarz** [comment]
@cortinico Should I file a pick request there also?

**Comment by cortinico** [comment]
Nope is just a reminder for us that there are 2 commits involved for this one 👍
