### ISSUE TITLE
[0.75] Update ignore file to include `ReactBuildConfig` in the npm package

### ISSUE THREAD

**Issue by j-piasecki** [reactwg/react-native-releases#357]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45279

### Description

Building from source is currently broken on Android due to the `ReactBuildConfig` file missing in the package. Linked PR fixes this.

**Comment by cipolleschi** [comment]
Picked ✅
