### ISSUE TITLE
[0.75] android autolinkLibrariesFromCommand should handle timeout or non zero exit code

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#368]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/3782511350c069425ad11cdefb8c6d3f10526fc2

### Description

This is a quality of life improvement for core autolinking which will be shipped in 0.75

**Comment by blakef** [comment]
Picked
