### ISSUE TITLE
[0.75] Fix PlatformConstants "prerelease" field

### ISSUE THREAD

**Issue by NickGerleman** [reactwg/react-native-releases#371]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/95d9cdf228e33d5651f41ebf5e14e80962fae118

### Description

Apart from fixing the typings on Android, this fixed up:
1. Fusebox reading the stamped field as a double (and crashing in published nightlies/RCs)
2. iOS returning a number (always 0) in PlatformConstants, which causes RSD to crash on current RC that doesn't have fix

**Comment by blakef** [comment]
Picked
