### ISSUE TITLE
[0.75] Pass the bridge proxy to ViewManagers on the New Architecture

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#372]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/d6c90cf7ed80caf0fc4eb2541f3dcadc3833dd37

### Description

This fixes the iOS Interop Layer which was not passing the BridgeProxy to view managers in Bridgeless mode.

**Comment by blakef** [comment]
Picked
