### ISSUE TITLE
[0.75] Upstream CLI `isPureCxxDependency` logic to RNGP

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#375]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/ca17d87ed1554ad023666c6971caaa5d3906807b

### Description

This brings the `isPureCxxDependency` logic to RNGP:
https://github.com/react-native-community/cli/pull/2387

**Comment by blakef** [comment]
Picked
