### ISSUE TITLE
[0.75] Allow library podspec to declare Swift Package Manager dependencies

### ISSUE THREAD

**Issue by RailByteOEBB** [reactwg/react-native-releases#377]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/f903f3483794f0e0e0b05ac24ab761344c319d6b

### Description

React-Native uses CocoaPods for native dependency management on iOS. While CocoaPods is flexible and popular, Apple's Swift Package Manager is the new standard. This commit enables consuming packages available only via Swift Package Manager. It would be a useful addition to 0.75

**Comment by blakef** [comment]
Picked
