### ISSUE TITLE
[0.74] Fix path to node in .xcode.env.local

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#387]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/8408b8bc96db15e265ca65fce7875ee65dcfdcec

### Description

When running `yarn ios` on Expo and with other tool, cocoapods creates an `.xcode.env.local` file that points to a temporary location for `yarn`. This simple change should fix this by ignoring temporary simlink to node and pointing to the right node path.

**Comment by Titozzz** [comment]
Picked !
