### ISSUE TITLE
[0.74] Add whitespace in compiler flags for RCTAppDelegate

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#393]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/be93092c1b8a079f74dcdc129afc3767f03b8a2e

### Description

This small change adds a whitespace between compiler flags to make sure that the project builds

**Comment by Titozzz** [comment]
Picked !
