### ISSUE TITLE
[0.75] remove setting of process.exitCode that breaks JS tests

### ISSUE THREAD

**Issue by douglowder** [reactwg/react-native-releases#396]
### Target Branch(es)

0.75, 0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45562

### Description

This fixes a CI issue that seems to prevent JS tests from returning success when running in CI (`scripts/run-ci-javascript-tests.js`).

**Comment by cipolleschi** [comment]
Picked! ✅
