### ISSUE TITLE
[0.74] remove setting of process.exitCode that breaks JS tests

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#397]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45562

### Description

This fixes a CI issue that seems to prevent JS tests from returning success when running in CI (`scripts/run-ci-javascript-tests.js`).

Reported originally by @douglowder

**Comment by Titozzz** [comment]
Picked !
