### ISSUE TITLE
Release 0.72.16

### ISSUE THREAD

**Issue by siddharthkul** [reactwg/react-native-releases#400]
### Target Minor

0.72

### Release Checklist

See [Release Process](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md) documentation

- [x] [Complete picks](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-2-cherry-pick-or-merge-requests-against-release-branch)
  - See [framework to evaluate priority of picks](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md#release-issues-and-pick-request-escalation)
- [x] (If < 0.74) [Publish monorepo packages](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-3-publish-monorepo-packages)
- [x] [Push things remote to get assets (like Hermes) ready](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-4-build-artifacts-on-circleci)
- [x] Test release (create [Test Report](https://github.com/reactwg/react-native-releases/issues/new/choose))
- [ ] (If > 0.74) [Publish monorepo packages](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-6-publish-monorepo-packages)
- [ ] [Publish `react-native`](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-7-publish-react-native)
- [ ] [Verify release](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-8-verify-release)
- [ ] [Update Changelog](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-9-generate-the-changelog-pr)
- [ ] [Create Github Release](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-10-create-the-github-release)
- [ ] [Announce it](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-11-communicate-release)
- [ ] [Update podfile.lock](https://github.com/reactwg/react-native-releases/blob/main/docs/guide-release-process.md#step-12-update-podfilelock-on-the-release-branch)
- [ ] Update any Github Projects

**Comment by mikeduminy** [comment]
We're stuck on 0.72 still and would love to get [this hermes change](https://github.com/facebook/hermes/commit/20b13b96f49c6819f6090f17a5ec29d3faec45c6) cherry-picked into the 72, 73, 74 and 75 branches. It fixes a problem with processing large bundles on-device (like in dev mode) and should be safe to cherry-pick as it contains isolated changes (see [comment](https://github.com/facebook/hermes/issues/1448#issuecomment-2260655659)).

**Comment by cortinico** [comment]
> We're stuck on 0.72

Why are you stuck on 0.72? 72 is end-of-life as we're about to ship 0.75 and is unlikely we'll pick such a change so late in the lifecycle of this release.

You can open a pick request for 0.75 though and we can discuss if we can pick it there, and if so pick it in other branches as well

**Comment by mikeduminy** [comment]
> Why are you stuck on 0.72?
Mostly competing priorities and library incompatibilities we need to solve. Ours is a complex app with lots of dependencies.

Realistically we won't be able to get to 74/75 any time soon. If landing this in 72 is a no-go then we can push forward our upgrade to 73, so we'd need it to land in 73 at least. Is that potentially possible?

**Comment by cortinico** [comment]
> If landing this in 72 is a no-go then we can push forward our upgrade to 73, so we'd need it to land in 73 at least. Is that potentially possible?

Potentially yes, but we'll first need to pick it in 0.75

**Comment by cipolleschi** [comment]
Failed to release, we have to release .17

**Comment by cipolleschi** [comment]
@mikeduminy I tried to pick the hermes pick in 0.72, but there are many conflicts and tests are not passing on Linux, so I don't think we can pick this on 0.72.

**Comment by mikeduminy** [comment]
Thanks for trying @cipolleschi
