### ISSUE TITLE
Severe Performance Degradation On Upgrading To RN 0.74

### ISSUE THREAD

**Issue by udasi-jew-peter** [reactwg/react-native-releases#405]
### Old Version

0.72.8

### New Version

0.74.3

### Description

We are noticing a massive performance degradation after upgrading to React Native 0.74.3. We were intending to try and enable the new architecture to help improve our app's performance but after upgrading React Native without the new architecture enabled, we are facing a performance issue. It is very obvious since navigation transitions seem to stutter, button interactions as well as lotties are janky. Even input field feels unresponsive for a few hundred milliseconds after entering 1 character.

### Steps to reproduce

I am not sure what steps to reproduce I can share, since I couldn't find any other issue mentioning this problem. All I did was upgrade React Native to 0.74.3 and upgrade some dependencies which were breaking and the problem happened. Moreover, we tried enabling New Architecture, and the problem got even worse.

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4
  CPU: (10) arm64 Apple M1 Pro
  Memory: 169.63 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.2
    path: ~/.nvm/versions/node/v18.20.2/bin/node
  Yarn:
    version: 3.2.0
    path: ~/.nvm/versions/node/v18.20.2/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v18.20.2/bin/npm
  Watchman:
    version: 2024.03.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

**Comment by cortinico** [comment]
> I am not sure what steps to reproduce I can share

Sadly we can't support you in any way without a reproducer @udasi-jew-peter

**Comment by cortinico** [comment]
We're closing all the "Type: Upgrade Issue" in this repo as we're using it only for pick requests.

If you're still having this problem, please open an issue on:
https://github.com/facebook/react-native/issues/new
