### ISSUE TITLE
[0.75] Filter out null dependencies from getGradleDependenciesToApply

### ISSUE THREAD

**Issue by gabrieldonadel** [reactwg/react-native-releases#407]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45749

### Description

we need to filter out platform-specific libraries from the auto-linking gradle plugin to prevent it from trying to call `implementation:` in a non supported lib

**Comment by cipolleschi** [comment]
Picked ✅
