### ISSUE TITLE
[0.75]  Fix core autolinking not working on Windows

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#409]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/fedbe2d48656e1196774ddaf3f52c70f1ef521cb

### Description

Core autolinking was broken on windows due to a missing `cmd /c` on the command line invocation. This fixes it

**Comment by cipolleschi** [comment]
This pr was done against main and the RNGP folder structure has changed.
@cortinico is working on a PR against 0.75.

**Comment by cipolleschi** [comment]
Picked ✅
