### ISSUE TITLE
[0.74] Remove duplicate legacy event

### ISSUE THREAD

**Issue by blakef** [reactwg/react-native-releases#414]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/34a50ae8ef559f309117d5b6abe0b68b2b349fa4

### Description

Reported in facebook/react-native#45513, there are duplicate events on `onChange`.  This has been resolved in 0.75 by the commit, but affects 0.74.

**Comment by Titozzz** [comment]
Picked
