### ISSUE TITLE
[0.74] Fix Hermes iOS version

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#415]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45840

### Description

This is a PR open against 0.74 to fix an issue where Apple versions were not inserted properly in the Hermes Plist.
https://github.com/facebook/react-native/issues/45823

**Comment by Titozzz** [comment]
Merged
