### ISSUE TITLE
[0.75] Add shared-testutil folder to NPM files to be published

### ISSUE THREAD

**Issue by gabrieldonadel** [reactwg/react-native-releases#425]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45936

### Description

React-native 0.75 RC7 gradle sync is currently broken due to the fact that the shared-testutil folder is missing from the @react-native/gradle-plugin npm package

**Comment by cipolleschi** [comment]
Picked ✅
