### ISSUE TITLE
[0.73] Cherry-pick "Fix path to node in .xcode.env.local"

### ISSUE THREAD

**Issue by av185218** [reactwg/react-native-releases#426]
### Target Branch(es)

0.73

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/43333

### Description

As our team works across multiple React Native projects at the same time, we experience quite frequently local iOS build failures due wrong node path within xcode.env.local file. Since we are not able to quickly migrate to the next 0.74 version that contains the fix, it would be nice if a cherry-pick would be made against 0.73.

Thank you in advance!

**Comment by cipolleschi** [comment]
Picked ✅
