### ISSUE TITLE
[0.75] Disable border radius percentage support in Android legacy arch

### ISSUE THREAD

**Issue by NickGerleman** [reactwg/react-native-releases#427]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/bbd5b5e1574499478ab0bf3fe9d2a21b02b7fedd

### Description

Wanting to pick to minimize the period where folks may rely on Android implementation which we decided to disable.

**Comment by cortinico** [comment]
Picked, will be out in 0.75.1 ✅
