### ISSUE TITLE
[0.75] Disable translation percentage support in Android legacy arch 

### ISSUE THREAD

**Issue by NickGerleman** [reactwg/react-native-releases#428]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/0273123dde04de72da4ebfeff26b0830eea00745

### Description

Wanting to pick to minimize the period where folks may rely on Android implementation which we decided to disable.

**Comment by cortinico** [comment]
Picked, will be out in 0.75.1 ✅
