### ISSUE TITLE
[0.75.2] Remove UIReturnKeyDefault from the list  

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#443]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/26aff664c07f129e64e60b42aa0c7eeaa79a93c3

### Description

This change removes the `UIReturnKeyDefault` because with it, some keyboard were showing an extra banner.

**Comment by blakef** [comment]
✅ Picked
