### ISSUE TITLE
[0.75] Cherry-pick `querystring` -> `URLSearchParams` migration

### ISSUE THREAD

**Issue by Vyazovoy** [reactwg/react-native-releases#448]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/d1bf828398f81c8bef6537004547a52260af76b4

### Description

It is pretty small change that fixes a deprecation warning "The querystring API is considered Legacy. new code should use the URLSearchParams API instead." so it would be good to get it published.

**Comment by cipolleschi** [comment]
Picked ✅
