### ISSUE TITLE
[0.74] Might fix "Animated node with tag (child) [x] does not exist"

### ISSUE THREAD

**Issue by dcangulo** [reactwg/react-native-releases#455]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45984/commits/b3967d31a33eb7aafbabae97e5278a8ea5564e42

### Description

The PR might fix "Animated node with tag (child) [x] does not exist". I don't have repro but it appears in Play Store issues, we'll just observe if the number of instances will go down with this PR.

https://github.com/facebook/react-native/issues/37267#issuecomment-2288908237

**Comment by blakef** [comment]
I can't pick for 0.74.6 this as the linked commit doesn't exist on any of branch on our repo:

![Image](https://github.com/user-attachments/assets/c6873aef-999f-4a78-b46d-f60aad07a038)

**Comment by migueldaipre** [comment]
> I can't pick for 0.74.6 this as the linked commit doesn't exist on any of branch on our repo:
> 
> ![Image](https://private-user-images.githubusercontent.com/49578/372137121-c6873aef-999f-4a78-b46d-f60aad07a038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTU2ODUsIm5iZiI6MTcyNzcxNTM4NSwicGF0aCI6Ii80OTU3OC8zNzIxMzcxMjEtYzY4NzNhZWYtOTk5Zi00YTc4LWI0NmQtZjYwYWFkMDdhMDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDE2NTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNmQ5NDczY2Q3YjcyMDRmODlmNjA2OWRhYWViZDYxMGVlYjBmZTFlMWY2OGE4ZWVjN2Y3MDM4M2ZmNGZiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YcK_3iHB4f-MpqyKAXn33S8xfS5dOaLJposmg3idnz8)

This is probably the right one https://github.com/facebook/react-native/commit/66ff4d3515ca148069a0a3d6c6744e1144d7a789

**Comment by dcangulo** [comment]
Here's the PR: https://github.com/facebook/react-native/pull/45984, it's tagged as "Merged".

**Comment by cihangir-mercan** [comment]
Hi, did it fix?
