### ISSUE TITLE
[0.74, 0.73, 0.72] Fix GH-41226 by suppressing path adjustment when not actually drawing a border

### ISSUE THREAD

**Issue by knappam** [reactwg/react-native-releases#457]
### Target Branch(es)

0.74, 0.73, 0.72

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45999

### Description

This is a backport of the pick request for 0.75 (https://github.com/reactwg/react-native-releases/issues/456) that is not in main because the affected filename changed between 0.74 and 0.75.  This fixes a pixelation issue that affects all of these versions.

I understand that 0.72 is closed, but would hugely appreciate taking this there.

**Comment by cortinico** [comment]
> 0.74, 0.73, 0.72

0.72 is unsupported so won't be picked there.

for 74 and 73 we need separate picks as they're executed at different times

**Comment by knappam** [comment]
Done: https://github.com/reactwg/react-native-releases/issues/474 and https://github.com/reactwg/react-native-releases/issues/473.  Closing this in favor of those.

**Comment by cipolleschi** [comment]
Can't pick in 0.73, as the codebase differs too much.
