### ISSUE TITLE
[0.75, 0.74, 0.73] fix(TypeScript): Allow readonly arrays in transform

### ISSUE THREAD

**Issue by tjzel** [reactwg/react-native-releases#462]
### Target Branch(es)

0.75, 0.74, 0.73

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46310

### Description

QoL type improvement for all RN versions, picking should be pretty much effortless. Not something very important though.

**Comment by cortinico** [comment]
> 0.75, 0.74, 0.73

You need to create separate pick requests for separate versions, as they're executed at different times
