### ISSUE TITLE
[0.76] Expose jsctooling via prefab

### ISSUE THREAD

**Issue by tomekzaw** [reactwg/react-native-releases#479]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46430

### Description

Reanimated needs to access libjsctooling.so so we need a prefab interface for it:

* https://github.com/facebook/react-native/pull/46430

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
