### ISSUE TITLE
[0.76] Debugger-frontend update to mitigate issues with highlighting elements from React DevTools

### ISSUE THREAD

**Issue by hoxyq** [reactwg/react-native-releases#483]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46401

### Description

> [!CAUTION]
This has to be picked **before** https://github.com/facebook/react-native/pull/46414

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
