### ISSUE TITLE
[0.76] Debugger-frontend update for React DevTools panels renaming

### ISSUE THREAD

**Issue by hoxyq** [reactwg/react-native-releases#484]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46414

### Description

> [!CAUTION]
> This has to picked **after** https://github.com/facebook/react-native/pull/46401 in https://github.com/reactwg/react-native-releases/issues/483

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
