### ISSUE TITLE
[0.76] Fix basic SVC validation

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#489]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/fad4a0783b0a0478c147d9bde2ef9ab082a08297

### Description

Recently we broke SVC validation in RNTester for some props.
This commit fixes the basic properties.

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
