### ISSUE TITLE
[0.76] Fix SVC for BoxShadow and Filter

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#490]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/de39a204c3588a3c02dc2e72464174c75b3a6749

### Description

This pick fixes the remaining SVCs

**Comment by NickGerleman** [comment]
This pick may depend on pick in https://github.com/reactwg/react-native-releases/issues/497

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
