### ISSUE TITLE
[0.76] Don't add the Privacy Manifest to the project twice

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#491]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/cadd41b1a2e16b1c77a8d3022f4ccbdbd5ea295f

### Description

There are some cases where we add the privacy manifest twice. This commit fixes those cases

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
