### ISSUE TITLE
[0.76] Unhide new arch layout props from TypeScript types

### ISSUE THREAD

**Issue by NickGerleman** [reactwg/react-native-releases#496]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/2d6c59e1d4f6ddb46373ed10c915aed4ce0c030c

### Description

We were hiding a bunch of layout props from TypeScript types which were only supported in new arch. Now that new arch will be default, we should make these visible (and document them on RN website, as a followup)

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
