### ISSUE TITLE
[0.76] Removing `experimental_` prefix from `boxShadow` and `filter` and type renaming

### ISSUE THREAD

**Issue by jorge-cab** [reactwg/react-native-releases#497]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

See Below

### Description

Officially releasing `filter` and `boxShadow`. Renaming types to more standard names.

https://github.com/facebook/react-native/commit/6b369a40d98c2bb7f933415f62b1e2b8f4da86ed
https://github.com/facebook/react-native/commit/2241c3146ffbfb8b77f54599b7cebb717537c15a
https://github.com/facebook/react-native/commit/6f84b63d64bf44eb096fd45b18491cc31b4e2436
https://github.com/facebook/react-native/commit/eaff327e0d5ee94cc11aeb6e3cd19320b61b2bed

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
