### ISSUE TITLE
[0.76] Restore `AnimatedNode.prototype.toJSON`

### ISSUE THREAD

**Issue by yungsters** [reactwg/react-native-releases#498]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46498

### Description

This pick request is necessary to unbreak inspection of `AnimatedNode` prop values with React DevTools.

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
