### ISSUE TITLE
[0.76] Fix Headless Crash Tried to finish non-existent task with id

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#499]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/b4532adad4e38e1237631778f7b8c917a9ccf746

### Description

Sometimes a headless task tries to finish, but it doesn’t exist, which causes an exception.
No one knows how to reliably reproduce it, as it could be a race condition. However, if you attempt to remove a task that has already been removed, it shouldn’t cause an issue since you're trying to remove something that’s already gone (which is exactly what you want)

**Comment by cortinico** [comment]
Picked, will land in 0.76.0 RC1 ✅
