### ISSUE TITLE
[0.76] Fix measuring text with incorrect hyphenationFrequency

### ISSUE THREAD

**Issue by NickGerleman** [reactwg/react-native-releases#518]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/fc8224036b4b5880c881f471e432ee5b47113b0b

### Description

Fixes a typo which causes incorrect text measurement on Android, randomly leading to text truncation in new arch.

**Comment by blakef** [comment]
Picked
