### ISSUE TITLE
[0.76] Fix <KeyboardAvoidingView> with floating keyboard on iPad 

### ISSUE THREAD

**Issue by renchap** [reactwg/react-native-releases#519]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/44859

### Description

Without this fix, if the user enabled a floating keyboard on an iPad any screen with `<KeyboardAvoidingView>` will have missing content and will result in a partially (large) blank screen.

**Comment by gkasireddy202** [comment]
@renchap - Can you please release this fix in react-native:0.73?

**Comment by cortinico** [comment]
> @renchap - Can you please release this fix in react-native:0.73?

@gkasireddy202 you need to create a different pick request for 0.73

**Comment by gkasireddy202** [comment]
@cortinico  - I just created a pick request for 0.73.
https://github.com/reactwg/react-native-releases/issues/520
