### ISSUE TITLE
[0.75] fix(react-native-xcode): Use CONFIG_CMD if set (#46112)

### ISSUE THREAD

**Issue by joe-sam** [reactwg/react-native-releases#521]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/774fe0cf6f22f832b756c166599973d9db6a93de

### Description

The --config-cmd is unnecessarily duplicated. 
This commit fixes it and has landed in 0.76 release candidates but has not yet been backported to RN 0.75.x where it is needed.

**Comment by blakef** [comment]
Picked
