### ISSUE TITLE
[0.75] Check if `type != NSNull` in readAsDataURL

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#522]
### Target Branch(es)

0.75

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/99ab845a5cf0fe3463ff39b03373b95d4f5c0fac

### Description

Bluesky fixed a bug where we were doing the wrong null-check on iOS

**Comment by blakef** [comment]
Picked
