### ISSUE TITLE
[0.76] Add CLI selection of multiple debug targets, CLI key handler fix

### ISSUE THREAD

**Issue by huntie** [reactwg/react-native-releases#524]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

4 PRs to merge in sequence:

1. https://github.com/facebook/react-native/pull/46643
2. https://github.com/facebook/react-native/pull/46644
3. https://github.com/facebook/react-native/pull/46645
4. https://github.com/facebook/react-native/pull/46646

### Description

These cover:

- Update Metro to latest release-aligned alpha.
- Add CLI selection of multiple debug targets (last JS-only addition planned for the open source React Native DevTools launch).
- Simplify key handling in start command — **fixes active user-reported issue from RC0**: https://github.com/facebook/react-native/issues/46571.

**Comment by blakef** [comment]
Merged.
