### ISSUE TITLE
[0.76] Fix applying of tintColor and progressViewOffset props for RefreshControl component

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#530]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/19d468fed966f2adb973ad3f19a97a5ec0372e3a

### Description

This commit properly implement a couple of props for the RefreshControl component in the New Architecture that were working in the Old Architecture.

**Comment by blakef** [comment]
Picked
