### ISSUE TITLE
[0.76] RNGP: Read enableWarningsAsErrors property correctly

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#534]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46657

### Description

This mitigates some of the issues users are reporting due to build issues on Android/Windows (such as this one https://github.com/facebook/react-native/issues/46210#issuecomment-2347057941)

**Comment by blakef** [comment]
Picked
