### ISSUE TITLE
[0.76] Fix ReactFragment crash on New Architecture 

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#536]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46675

### Description

Please merge the PR against the release branch, as otherwise merging this will create conflicts.

See more context on this crash here:
https://github.com/facebook/react-native/issues/46566

**Comment by blakef** [comment]
Merged
