### ISSUE TITLE
[0.76] Fix compiling new app when `transformer.hermesParser = false`

### ISSUE THREAD

**Issue by huntie** [reactwg/react-native-releases#538]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

**Strictly required** (in order)
- 1/ https://github.com/facebook/react-native/pull/46699
- 2/ https://github.com/facebook/react-native/pull/46696

**Optional 3rd PR** (recommended as this keeps `hermes-parser` aligned across the board)
- 3/ https://github.com/facebook/react-native/pull/46700

### Description

Resolves https://github.com/facebook/react-native/issues/46601.

**Comment by huntie** [comment]
@blakef @cortinico This stack is now ready (should land on `main` soon).

**Comment by cortinico** [comment]
cc @cipolleschi also

**Comment by blakef** [comment]
Picked all 3.
