### ISSUE TITLE
[0.73] RGNP - Remove unnecessary dependency on gradle-tooling-api-builders - serviceOf failure

### ISSUE THREAD

**Issue by ShivamGoyal1899** [reactwg/react-native-releases#557]
### Target Branch(es)

0.73

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46367

### Description

This fixes this bug in React Native 0.73:

- https://github.com/facebook/react-native/issues/32858

**Comment by cipolleschi** [comment]
Picked ✅
