### ISSUE TITLE
[0.76] Fix errors with component stacks reported as warnings

### ISSUE THREAD

**Issue by huntie** [reactwg/react-native-releases#560]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/46637

### Description

This is a desirable (although optional) pick request that changes the default behaviour of `LogBox.setWarningFilter()`, which could lead to [confusing behaviour](https://github.com/facebook/react-native-website/pull/4245) when combined with React Native DevTools changes around LogBox.

PRs (originally to `main`) to pick in order:

- https://github.com/facebook/react-native/pull/46639
- https://github.com/facebook/react-native/pull/46636
- https://github.com/facebook/react-native/pull/46638
- https://github.com/facebook/react-native/pull/46637

(⬆️ If needed, changes could be more granularly selected, but I don't anticipate conflicts in this section of the codebase.)

**Comment by blakef** [comment]
https://github.com/facebook/react-native/commit/1787726bf9e8cf58f5ccdbe42fad4d54f0081925
https://github.com/facebook/react-native/commit/2f85e28cdef87f59fd601a61d5726095b600a556
https://github.com/facebook/react-native/commit/e9ec9fbde480655b2c5a5a9b89e33485fb1335ca
https://github.com/facebook/react-native/commit/cbb313253fdf96c4fca06a24ed4cbd3f3df9db80

**Comment by blakef** [comment]
I'm reverting these from RC4, the unit tests are unfortunately failing: https://github.com/facebook/react-native/actions/runs/11217965745/job/31180674552#step:3:766

**Comment by blakef** [comment]
@huntie we're skipping this for 0.76.1 because nothing has changed (so we think the tests will continue to fail).  If you think this should go in 0.76.2, please update so it'll pass CI.

**Comment by blakef** [comment]
Use #607 to track.
