### ISSUE TITLE
[0.76] Replace uses of CGColorRef with UIColor to avoid manual memory management

### ISSUE THREAD

**Issue by Saadnajmi** [reactwg/react-native-releases#572]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/b70709dbc27c75c69e9fd2b082ffa27e7e8db7fd

### Description

Change made to help React Native macOS while merging up to RN 0.76

**Comment by blakef** [comment]
Hi @Saadnajmi, it looks like this was [backed out](https://github.com/facebook/react-native/commit/b0e2cb3371d303301b77fcab2cc7f5002d209268) last week.  Can you work with @joevilches to see / understand why it was reverted.  I think we'd look at this for either 0.77 (if it's a nice to have) or 0.76.1 (if it contains bug fixes, etc...).

Please reopen if I've got it wrong.

**Comment by joevilches** [comment]
@blakef Yeah we are in sync as to why it was reverted. It's an internal issue I am going to put up a PR fixing it with some things we discussed in the backout PR - just needed some things to settle last week which they mainly have

**Comment by blakef** [comment]
Checked again this morning before picking for 0.76.0-rc.5, but the updated changes in https://github.com/facebook/react-native/pull/47019 were still breaking internal tests.  Thanks @joevilches and @Saadnajmi for sticking with this.  We'll try again on 0.77.
