### ISSUE TITLE
[0.76] Android New Arch HeadlessJsTaskService EventEmitter Fix

### ISSUE THREAD

**Issue by lovegaoshi** [reactwg/react-native-releases#581]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/45100 and https://github.com/facebook/react-native/pull/46480

### Description

https://github.com/facebook/react-native/pull/45100 and https://github.com/facebook/react-native/pull/46480 together fixes HeadlessJsTaskService not able to initialize in android new arch. This is crucial to RN apps using services (like [RNTP](https://github.com/lovegaoshi/react-native-track-player)) wanting to migrate to the new arch. relevant discussions at https://github.com/facebook/react-native/issues/46050 and https://github.com/facebook/react-native/issues/44255

**Comment by gituser8796** [comment]
@cortinico can this one get in?

**Comment by cortinico** [comment]
> @cortinico can this one get in?

We haven't discussed this yet, but anyway if we decide to include it, it will go in 0.76.1

**Comment by gituser8796** [comment]
> > @cortinico can this one get in?
> 
> We haven't discussed this yet, but anyway if we decide to include it, it will go in 0.76.1

Ok thank you! We would appreciate it if this can get into 0.76.1

**Comment by AlexanderHott** [comment]
+1 for scheduling it for 0.76.1. I'm using RNTP and would like to migrate my app to the new arch.

**Comment by contactsimonwilson** [comment]
> +1 for scheduling it for 0.76.1. I'm using RNTP and would like to migrate my app to the new arch.

I'm in the same boat but for react-native-background actions.

**Comment by blakef** [comment]
facebook/react-native#45100 was already in 0.76,  facebook/react-native#46480 picked.
