### ISSUE TITLE
[0.76] Undo breaking change on ViewManagerDelegate.kt String params

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#582]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/47086

### Description

This is undoing a breaking change on `ViewManagerDelegate` which we shouldn't ship in 0.76, so let's pick this commit please

**Comment by cipolleschi** [comment]
Picked ✅
