### ISSUE TITLE
[0.76] Add jsBundleFile to DefaultReactNativeHost

### ISSUE THREAD

**Issue by sunnylqm** [reactwg/react-native-releases#593]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/47188

### Description

The JsBundleFilePath has been ignored when converting DefaultReactNativeHost to ReactHost

**Comment by cortinico** [comment]
@sunnylqm out of curiousity, why do you need this pick? What's your use case?

**Comment by sunnylqm** [comment]
for hot update(like codepush)
