### ISSUE TITLE
[0.76.2] Logbox show errors as errors not warnings

### ISSUE THREAD

**Issue by blakef** [reactwg/react-native-releases#607]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/47303

### Description

DX have asked that we merge this PR in to resolve an issue where logs are being shown at an incorrect level to users.  This has resolved the test issues that caused this to be excluded from the RC phase of 0.76.

**Comment by cipolleschi** [comment]
Picked ✅
