### ISSUE TITLE
[0.77][iOS][Hermes] Intl.DateTimeFormat.formatToParts() is undefined (again)

### ISSUE THREAD

**Issue by blakef** [reactwg/react-native-releases#623]
### Target Branch(es)

0.77

### Link to commit or PR to be picked

https://github.com/facebook/hermes/commit/c2c4ee7dfcf4b006268ee215b63f79e9cbeedcf4

### Description

Related to #290 and #618

It seems like `Intl.DateTimeFormat.formatToParts()` is removed but this change is not well communicated. The revert was picked for 0.74 and should be picked for 0.76 while the issue is being worked on.

## Note:
Our hope is that this is already in `main` on Hermes when we cut 0.77, but this is here to confirm and pick if it isn't.

**Comment by robhogan** [comment]
This was indeed already in Hermes main by the 0.77 cut, and I've verified `Hermes.DateTimeFormat` works in 0.77.0-rc.0. Closing - thanks for the reminder!
