### ISSUE TITLE
[0.76] Revert to @babel/eslint-parser in eslint-config

### ISSUE THREAD

**Issue by huntie** [reactwg/react-native-releases#629]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/47333

### Description

Paired change with https://github.com/facebook/react-native/pull/47569 (already merged).

This will restore the pre-0.76.0 behaviour of `.js|.jsx` files under ESLint in user code. `@babel/eslint-parser` will respect a local `babel.config.js` file (Babel pipeline), instead of the hermes-parser pipeline.

Changelog:
[General][Fixed] - Update `@react-native/babel-preset` to use `@babel/eslint-parser`, fixing compatibility with customised Babel configs (pre-0.76.0 behaviour)

### Test plan

See https://github.com/facebook/react-native/pull/47569 for context and setup.

Changes to `babel.config.js` (in this example, adding `@babel/plugin-proposal-decorators`) will now be used by ESLint.

| Before | After |
|--------|--------|
| <img width="678" alt="image" src="https://github.com/user-attachments/assets/2f4dc82e-9107-4e30-92b0-e8d32a24d3b7"> | <img width="669" alt="image" src="https://github.com/user-attachments/assets/d7e4dd5a-c6b9-4bc7-95f0-da00177aa86b"> | 
| ❌ Fails to parse | ✅ Reads project Babel config, parses with `@babel/plugin-proposal-decorators` |

**Comment by blakef** [comment]
Had a conflict.  Resolved.
