### ISSUE TITLE
[0.77.0-rc.0] Test Report

### ISSUE THREAD

**Issue by vonovak** [reactwg/react-native-releases#643]
### Target Minor

0.77

### Tested configurations

Refer to this [spreadsheet](https://docs.google.com/spreadsheets/d/1p0Zs37ecau7Ty4L_4g1jf7PlivOmIEPjmDYq9Jp8qWI/edit?usp=sharing) for test cases.

_more cases will be filled later_

- [x] RNTester + iOS + Hermes

I have ruby 3.3 installed and get (btw: https://formulae.brew.sh/formula/ruby@2.7)

```
bundler: failed to load command: pod (/opt/homebrew/lib/ruby/gems/3.3.0/bin/pod)
/opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/bundler/resolver.rb:354:in `raise_not_found!': Could not find gem 'activesupport (>= 6.1.7.5, < 7.1.0)' in locally installed gems. (Bundler::GemNotFound)

The source contains the following gems matching 'activesupport':
  * activesupport-7.2.2
	from /opt/homebrew/Cellar/ruby/3.3.6/lib/ruby/3.3.0/bundler/resolver.rb:445:in `block in prepare_dependencies'
```

otherwise ok after using ruby 2.7

- [x] RNTester + iOS + JSC
- [x] RNTester + Android + Hermes

tested on a real device (honor 20 pro, android 10)

summary: minor Text issues, endless reload loop when trying to connect to debugger (=> I didn't test its debugging features), redbox with "ERROR  StaticViewConfigValidator: Invalid static view config for ..."

<details>
<summary>Details</summary>

![Screenshot_20241126_105752_com facebook react uiapp](https://github.com/user-attachments/assets/309f97df-6097-4e35-a3bb-a2fdb663114e)
![Screenshot_20241126_105719_com facebook react uiapp](https://github.com/user-attachments/assets/d64c5978-55b3-4a28-ad94-01ac410b2936)

endless loop:

```
endless loop when pressing (j) and (3)  React Native Experimental (Improved Chrome Reloads). the "No compatible apps connected" was shown when pressing (1) and (2) for the available options.

 INFO  Launching DevTools...
 WARN  No compatible apps connected. React Native DevTools can only be used with the Hermes engine.
 INFO  Launching DevTools...
 WARN  No compatible apps connected. React Native DevTools can only be used with the Hermes engine.
 INFO  Launching DevTools...
 MAP  js/RNTesterApp.android.js 

 MAP  js/RNTesterApp.android.js 

 MAP  js/RNTesterApp.android.js 
...
```

redbox:

```
 (NOBRIDGE) ERROR  StaticViewConfigValidator: Invalid static view config for 'RCTView'.

- 'validAttributes.experimental_boxShadow' is missing.
- 'validAttributes.experimental_mixBlendMode' is missing.
- 'validAttributes.experimental_filter' is missing.
 (NOBRIDGE) ERROR  StaticViewConfigValidator: Invalid static view config for 'RCTImageView'.

- 'validAttributes.experimental_boxShadow' is missing.
- 'validAttributes.defaultSrc' is missing.
- 'validAttributes.experimental_mixBlendMode' is missing.
- 'validAttributes.experimental_filter' is missing.
 (NOBRIDGE) ERROR  StaticViewConfigValidator: Invalid static view config for 'AndroidTextInput'.

- 'validAttributes.experimental_boxShadow' is missing.
- 'validAttributes.experimental_mixBlendMode' is missing.
- 'validAttributes.experimental_filter' is missing.
 (NOBRIDGE) ERROR  StaticViewConfigValidator: Invalid static view config for 'RCTScrollView'.

- 'validAttributes.experimental_boxShadow' is missing.
- 'validAttributes.experimental_mixBlendMode' is missing.
- 'validAttributes.experimental_filter' is missing.
- 'validAttributes.enableSyncOnScroll' is missing.
 (NOBRIDGE) ERROR  StaticViewConfigValidator: Invalid static view config for 'DebuggingOverlay'.

- 'validAttributes.experimental_mixBlendMode' is missing.
- 'validAttributes.experimental_filter' is missing.
 (NOBRIDGE) ERROR  StaticViewConfigValidator: Invalid static view config for 'AndroidHorizontalScrollContentView'.

- 'validAttributes.experimental_mixBlendMode' is missing.
- 'validAttributes.experimental_filter' is missing.
 (NOBRIDGE) ERROR  StaticViewConfigValidator: Invalid static view config for 'AndroidHorizontalScrollView'.

- 'validAttributes.experimental_boxShadow' is missing.
- 'validAttributes.experimental_mixBlendMode' is missing.
- 'validAttributes.experimental_filter' is missing.
- 'validAttributes.enableSyncOnScroll' is missing.
 (NOBRIDGE) ERROR  StaticViewConfigValidator: Invalid static view config for 'AndroidSwitch'.
```

</details>

- [x] RNTester + Android + JSC

hasOwn error, as already reported

- [x] RNTestProject + iOS + Hermes
- [x] RNTestProject + iOS + JSC
- [x] RNTestProject + Android + Hermes
- [x] RNTestProject + Android + JSC

Close this issue if there are no blocking issues.

### Blocking Issues?

- I believe we should support ruby 3.x; I haven't tested with 3.0, but 3.3 doesn't seem to work?
- ERROR StaticViewConfigValidator: Invalid static view config for ... - though app seems working okay

**Comment by robhogan** [comment]
> ### Blocking issues?
>  - I believe we should support ruby 3.x; I haven't tested with 3.0, but 3.3 doesn't seem to work?
>  - ERROR StaticViewConfigValidator: Invalid static view config for ... - thought app seems working okay

IMO the bar for a release-blocking issue for rc.0 is higher than this, we need a stationary target to start stabilising, and rc.0 only needs to be good enough to test with.
