### ISSUE TITLE
[0.76] Fabric: Fixes Modal onRequestClose not called

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#648]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/28ced2e5588961008c0116ed81ff40145e6682e2

### Description

This implement a missing API that we had in the Old Architecture but not in the New Architecture.

**Comment by blakef** [comment]
Had conflicts that were resolved.  There's a change in here that was reverted in 0.77: https://github.com/facebook/react-native/pull/46433, I wonder if we need to do the same in 0.76.4?
