### ISSUE TITLE
[0.76] [Android/ Fabric] Avoid NPE when touch event is triggered before SurfaceManager is initiated 

### ISSUE THREAD

**Issue by CHOIMINSEOK** [reactwg/react-native-releases#656]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/48007

### Description

This is 100% reproduciable issue that could cause non-trivial crash on 1M+ MAU services which try to adopt React Native new arch

**Comment by blakef** [comment]
@javache  supported this pick.
