### ISSUE TITLE
[0.76] Fixes insets not adjusting when keyboard disappear

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#658]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/efcfe5dcd6626efbbac3f92e4d842e843aea7d77

### Description

We have a bug where the insets applied to a scroll view when the keyboard appears on screen were not reset to the previous value when the keyboard disappear.

This commit should fix that behavior.

**Comment by blakef** [comment]
@cipolleschi  This commit is missing from 0.76, for this fix to make sense: https://github.com/facebook/react-native/commit/2d9933e616c3efe57ed0ca141277638182a69d9c, it was only in 0.77.  I'm going to pick that and see if it resolves the iOS compilation issues on this branch.
