### ISSUE TITLE
[0.76] Revert "Include autolinkin.h in OnLoad.cpp only if it exists

### ISSUE THREAD

**Issue by cortinico** [reactwg/react-native-releases#667]
### Target Branch(es)

0.76

### Link to commit or PR to be picked

https://github.com/facebook/react-native/pull/48156

### Description

This is currently blocking reanimated as it's preventing the autolinked modules from being loaded. The fix is sadly not correct because the OnLoad.cpp file is available ONLY on New Architecture and the <autolinking.h> is always generated.

**Comment by sunnylqm** [comment]
i think this is blocking all autolinked modules on android
