### ISSUE TITLE
[0.77] Fix crash in old architecture in cold start launches from the background

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#669]
### Target Branch(es)

0.77

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/3c747eb037d4a5c727da3a47803d8e4cd2c5b80d

### Description

In the old architecture, when the app is launched from background due to a notification, it can sometime crash.  This commit fixes that case.

**Comment by blakef** [comment]
https://github.com/facebook/react-native/commit/4560fc049748a345d5945bc08d43f4b61ca51ff3
