### ISSUE TITLE
[0.77-rc.3] Revert "Include autolinkin.h in OnLoad.cpp only if it exists

### ISSUE THREAD

**Issue by vonovak** [reactwg/react-native-releases#674]
### Target Branch(es)

0.77-stable

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/94e2b5b1b46bd6e9a3e0655b0ecac0e8e6501897

### Description

see https://github.com/reactwg/react-native-releases/issues/667

**Comment by cipolleschi** [comment]
Picked ✅
