### ISSUE TITLE
[0.77] Fix Android JSC compatibility - replaceAll -> replace 

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#696]
### Target Branch(es)

0.77

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/b5b9e032c2b57aa44afb7141a879d83c8b889feb

### Description

JSC for Android does not implement `String.prototype.replaceAll`.

https://github.com/facebook/react-native/pull/47466 introduced a use of it into runtime code, breaking JSC compatibility.

This.. replaces it.. with `replace`. Since the argument is already a regex with a `g` modifier, `replaceAll` wasn't necessary anyway.

**Comment by robhogan** [comment]
(Context: this was my commit to main)

Closing this one without pick as discussed, because this JS isn't actually reachable in 0.77, where `useAlwaysAvailableJSErrorHandling` is feature-flagged off.
